/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from 'react'

import { folder, useControls } from 'leva'

import { useGLTF, useTexture } from '@react-three/drei'

import { useRoomAnimations } from '../../hooks'
import { Books, Desk, Guitar, Lavagna, LeftMonitor, Quadro, RightMonitor, ShadowCatcher } from './components'

import './materials'

export function RoomV8(props) {
  // Room Nodes
  const { nodes } = useGLTF('./models/room_v8/desk/room.glb')

  // Textures
  const bakedTexture = useTexture('./models/room_v8/desk/room_baked.jpg')
  bakedTexture.flipY = false

  // Refs
  const desk = useRef()
  const guitar = useRef()
  const books = useRef()
  const quadro = useRef()
  const lavagna = useRef()
  const shadowCatcher = useRef()

  // Evita che l'oggetto venga ricreato ad ogni render
  const refs = useMemo(() => ({ desk, guitar, books, quadro, lavagna, shadowCatcher }), [])

  // Controls
  var { position, rotation } = useControls('Room V8', {
    desk: folder(
      {
        position: { value: props.position || [0, 0, 0], max: 10, step: 0.01 },
        rotation: { value: props.rotation || [0, 0, 0], max: 10, step: 0.01 }
      },
      { collapsed: true }
    )
  })

  // Room Animations
  useRoomAnimations(refs)

  return (
    <group {...props} position={position} rotation={rotation} dispose={null}>
      {/* Desk */}
      <group ref={desk}>
        <Desk geometry={nodes.desk.geometry} bakedTexture={bakedTexture} />

        <LeftMonitor geometry={nodes.left_monitor.geometry} />
        <RightMonitor geometry={nodes.right_monitor.geometry} />
      </group>

      {/* Stuff */}
      <Books ref={books} geometry={nodes.books.geometry} bakedTexture={bakedTexture} />
      <Guitar ref={guitar} geometry={nodes.guitar.geometry} bakedTexture={bakedTexture} />
      <Lavagna ref={lavagna} geometry={nodes.lavagna.geometry} bakedTexture={bakedTexture} />
      <Quadro ref={quadro} geometry={nodes.quadro.geometry} bakedTexture={bakedTexture} />

      {/* ShadowCatcher */}
      <ShadowCatcher ref={shadowCatcher} />
    </group>
  )
}

useGLTF.preload('./models/room_v8/desk/room.glb')
useTexture.preload('./models/room_v8/desk/room_baked.jpg')
