export { Books } from './Books'
export { Desk } from './Desk'
export { Guitar } from './Guitar'
export { Quadro } from './Quadro'
export { Lavagna } from './Lavagna'
export { ShadowCatcher } from './ShadowCatcher'
export { LeftMonitor } from './LeftMonitor'
export { RightMonitor } from './RightMonitor'
